### USER REGISTER
POST http://localhost:6000/user-api/users
Content-Type: application/json

{
  "firstName": "Gudladona",
  "lastName": "Greeshma",
  "email": "anurag.user@example.com",
  "password": "User@12345",
  "profileImageUrl": "https://example.com/avatars/user.png"
}


### USER LOGIN
POST http://localhost:6000/common-api/authenticate
Content-Type: application/json

{
  "email": "anurag.user@example.com",
  "password": "User@12345",
  "role": "USER"
}


### AUTHOR REGISTER
POST http://localhost:6000/author-api/users
Content-Type: application/json

{
  "firstName": "greesh",
  "lastName": "Author",
  "email": "greesh.author@example.com",
  "password": "Author@12345",
  "profileImageUrl": "https://example.com/avatars/author.png"
  
}


### AUTHOR LOGIN
POST http://localhost:6000/common-api/authenticate
Content-Type: application/json

{
  "email": "greesh.author@example.com",
  "password": "Author@12345",
  "role": "AUTHOR"
}


### CREATE ARTICLE (AUTHOR)
POST http://localhost:6000/author-api/articles/698acd4dd05185eea591f25e
Content-Type: application/json

{
  "title": "test2 article",
  "category": "programming",
  "content": "content of test2 article"
}


### READ ARTICLES OF AN AUTHOR
GET http://localhost:6000/author-api/articles/698acd4dd05185eea591f25e


### READ ACTIVE ARTICLES OF AUTHOR
GET http://localhost:6000/author-api/articles/active/698acd4dd05185eea591f25e

### UPDATE ARTICLE (AUTHOR)
PUT http://localhost:6000/author-api/articles/698acde0d05185eea591f262/698acd4dd05185eea591f25e
Content-Type: application/json

{
  "title": "test2 article updated",
  "category": "programming",
  "content": "content of test2 article updated"
}

### DELETE ARTICLE (AUTHOR)
DELETE http://localhost:6000/author-api/articles/698acde0d05185eea591f262/698acd4dd05185eea591f25e

### USER – READ ALL ARTICLES
GET http://localhost:6000/user-api/articles/698ac7d961f284b6486170f7

### USER – ADD COMMENT
PUT http://localhost:6000/user-api/articles/698acde0d05185eea591f262/comments/698ac7d961f284b6486170f7
Content-Type: application/json

{
  "comment": "Very useful article!"
}

### LOGOUT
POST http://localhost:6000/common-api/logout

### CHANGE PASSWORD
PUT http://localhost:6000/common-api/change-password/698ac3660776df77d73be3cb
Content-Type: application/json

{
  "currentPassword": "admin123",
  "newPassword": "admin"
}

